---
title: "SFA1 - DOC analysis"
author: "Cassi Wattenburger"
date: "3/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(results = "hide")
```

**Goal of this script:** Identify high and low DOC-producing communties from soil microcosms

```{r}
rm(list=ls())

library(plyr)
library(tidyverse)
require(broom)
library(reshape2)
library(car)
```

```{r}
# Import data
rep1.avg=read.csv("../data_DOC/SFA1/SFA1_DOC_1-51_processed_summary.csv")
rep2.avg=read.csv("../data_DOC/SFA1/SFA1_DOC_52-102_processed_summary.csv")
rep3.avg=read.csv("../data_DOC/SFA1/SFA1_DOC_103-153_processed_summary.csv")

# Import metadata
meta=read.csv("../data_DOC/SFA1/SFA1_DOC_metadata.csv")
```

```{r, results="show"}
# Combine reps
data=rbind(rep1.avg, rep2.avg, rep3.avg)

# Add metadata
DOC.data=merge(data, meta, by.x="Sample.ID", by.y="Microcosm", all=TRUE)
```

```{r, eval=FALSE}
save(DOC.data, file="~/SFAgrowthrate/SFAphase1/r.output/SFA1_DOC.data.RData")
```

```{r}
# Summarize replicates
data.melt=melt(DOC.data[,c(2,3,6)], id.vars=c("s.type","Soil.sample"))
data.smry=ddply(data.melt, c("Soil.sample","s.type"), summarize, avg=mean(value), stdv=sd(value))

# Relevel sample id factors
data.melt$Soil.sample=ordered(data.melt$Soil.sample, levels=c("Abiotic", "Blank", "1","2","3","4","5","6","7","8","9","10", "11","12","13","14","15","16","17","18","19","20", "21","22","23","24","25","26","27","28","29","30", "31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51"))

data.smry$Soil.sample=ordered(data.smry$Soil.sample, levels=c("Abiotic", "Blank", "1","2","3","4","5","6","7","8","9","10", "11","12","13","14","15","16","17","18","19","20", "21","22","23","24","25","26","27","28","29","30", "31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51"))

# graph
ggplot(data.smry, aes(x=Soil.sample, y=avg, color=s.type)) +
  geom_point() +
  geom_errorbar(aes(ymin=avg-stdv, ymax=avg+stdv)) +
  labs(title="DOC samples", x="Sample", y="DOC (ppm)")

ggplot(data.melt, aes(y=value, x=Soil.sample, color=s.type)) +
  geom_boxplot(aes(Soil.sample)) +
  labs(title="DOC samples", x="Sample", y="DOC (ppm)")

```

Convert ppm to mg

```{r}
# 10 mL used to extract DOC from microcosm
data.smry = mutate(data.smry, mgDOC = 10*avg*10^-6*1000,
                   data.smry, mgDOC2 = (10*avg)/1000) # 10 mL of water used to extract, avg is in ppm, *10^-6 converts to proportion, *1000 converts g to mg
```


```{r, eval=FALSE, include=FALSE}
# Save data
DOC.melt=data.melt
save(DOC.melt, file="~/SFAgrowthrate/SFAphase1/r.output/SFA1_DOC.melt.RData")

DOC.smry=data.smry
save(DOC.smry, file="~/SFAgrowthrate/SFAphase1/r.output/SFA1_DOC.smry.RData")
```

```{r, results="show"}
# Top 3 vs bottom 3 by avg DOC concentration
data.smry.bottom3=arrange(data.smry[data.smry$s.type=="Sample",], avg)
data.smry.bottom3=data.smry.bottom3[1:3,]
data.smry.bottom3$rank=rep("low", nrow(data.smry.bottom3))

data.smry.top3=arrange(data.smry[data.smry$s.type=="Sample",], desc(avg))
data.smry.top3=data.smry.top3[2:4,] # top place is the control so skip row 1
data.smry.top3$rank=rep("high", nrow(data.smry.top3))

# Merge top and bottom 3 into dataframe
data.smry.tb = rbind(data.smry.bottom3, data.smry.top3)

# Graph
ggplot(data.smry.tb, aes(x=Soil.sample, y=avg, color=rank)) +
  geom_point() +
  geom_errorbar(aes(ymin=avg-stdv, ymax=avg+stdv))

# Do the same but for melted data format (want to make boxplots because they're better for representing data)
highlow=data.smry.tb$Soil.sample
data.melt.tb=data.melt[data.melt$Soil.sample==50 | data.melt$Soil.sample==4  | data.melt$Soil.sample==31  | data.melt$Soil.sample==32  | data.melt$Soil.sample==17  | data.melt$Soil.sample==42,] # not sure why I had to do it this stupid way ugh
data.melt.tb=mutate(data.melt.tb, rank=ifelse(Soil.sample==4 | Soil.sample==42 | Soil.sample==50, "high", "low"))

# Graph
ggplot(data.melt.tb, aes(x=Soil.sample, y=value, color=rank)) +
  geom_boxplot() +
  labs(title="High vs low DOC samples", x="Sample", y="DOC (ppm)")
```

```{r, results="show"}
# Statistics

# Is the data normal?
shapiro.test(data.smry.tb$avg) # yes
shapiro.test(data.melt.tb$value) # yes

# Equal variances?
leveneTest(avg ~ rank, data.smry.tb) # yes
leveneTest(value ~ rank, data.melt.tb) # yes

# Is high statistically distinct from low DOC?
test.melt=lm(value~rank, data.melt.tb)
summary(test.melt) # significant
test.smry=lm(avg~rank, data.smry.tb)
summary(test.smry) # signficant

# graph
ggplot(data.melt.tb, aes(x=rank, y=value)) +
  geom_boxplot() +
  labs(title="High vs low DOC samples", x="", y="DOC (ppm)") +
  annotate("text", x=2, y=1500, label="ANOVA \n P-value=0.0001")
```