---
title: "SFA2 beta diversity"
author: "Cassandra Wattenburger"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results = "show")
knitr::opts_chunk$set(message = FALSE)
```

```{r}
# Clear working directory, load in packages, generate package info
rm(list=ls())

library("tidyverse")
library("ape")
library("phyloseq")
library("picante")

sessionInfo()
```

# Import data

* Rarefied phyloseq object (1500 counts)
* growth estimates

```{r}
# Phyloseq object with all growth samples
physeq <- readRDS("../data_intermediate/SFA2_physeq_rare.rds")

# Metadata
meta <- data.frame(sample_data(physeq))

# Growth estimates
growth <- readRDS("../data_intermediate/SFA2_growth_estimates_pap.rds")
```

# Phylogenetic dispersion

Weighted unifrac distances:

```{r}
# Calculate wunifrac distance
wuni_dist <- distance(physeq, method="wunifrac")

meta_sub <- select(meta, SampleID, Inoculant, Day)

# Reformat
wuni_df <- wuni_dist %>% 
  as.matrix() %>% 
  as.data.frame() %>%
  rownames_to_column(var="Sample1") %>% 
  pivot_longer(-Sample1, names_to = "Sample2", values_to = "wuni_dist")

wuni_df <- wuni_df[wuni_df$Sample1 != wuni_df$Sample2,] # remove self-comparisons
```

Remove duplicate pairwise comparisons:

SLOW STEP, run manually

```{r, eval=FALSE}
# Remove duplicates
# SLOW
# Sort sample1 and sample2 to create a unique label for duplicates regardless of order in columns
all_labels <- as.character()
for (i in 1:nrow(wuni_df)) {
  string <- wuni_df[i,] %>% 
    select(Sample1, Sample2) %>% 
    as.character() %>% 
    sort()
  label <- paste0(string[1], string[2])
  all_labels <- append(all_labels, label)
}

wuni_df2 <- bind_cols(wuni_df, all_labels) %>% 
  select(wuni_dist, label=`...4`) %>% 
  distinct() %>% # remove duplicate pairwise comparisons!
  mutate(Sample1 = gsub("(sa[0-9]+)(sa[0-9]+)", "\\1", label),
         Sample2 = gsub("(sa[0-9]+)(sa[0-9]+)", "\\2", label)) %>% 
  select(Sample1, Sample2, wuni_dist)

saveRDS(wuni_df2, "../data_intermediate/SFA2_wunidist_slim.rds")
```

```{r, eval=FALSE}
wuni_df <- readRDS("../data_intermediate/SFA2_wunidist_slim.rds")

# Comparisons of interest
wuni_within <- data.frame()
for (i in unique(meta$Inoculant)) {
  for (d in unique(meta[meta$Inoculant==i,]$Day)) {
    sams <- filter(meta, Inoculant==i & Day==d) 
    sams <- sams$SampleID
    wuni_sub <- filter(wuni_df, Sample1 %in% sams & Sample2 %in% sams) # isolate samples of interest
    wuni_avg <- mean(wuni_sub$wuni_dist) # average
    this_row <- bind_cols(Inoculant=i, Day=d, wuni_dist=wuni_avg)
    wuni_within <- bind_rows(wuni_within, this_row)
  }
}

# Visualize
wuni_within %>% 
  ggplot(aes(x=Day, y=wuni_dist)) +
  geom_line(aes(group=Day)) +
  geom_point(aes(color=Inoculant)) +
  labs(y="Weighted unifrac distance (between replicates)") +
  theme_test()

wuni_within %>% 
  ggplot(aes(x=Day, y=wuni_dist, color=Inoculant)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Inoculant) +
  labs(y="Weighted unifrac distance (between replicates)") +
  theme_test
```

```{r, eval=FALSE}
saveRDS(wuni_within, "../data_intermediate/SFA_wunidist_withinreps.rds")
```


# Ordinations

## Overall

NMDS ordination:

```{r}
# Graph formatting to color time points
meta_format <- data.frame(sample_data(physeq)) %>% 
  mutate(leveloff = if_else(Day >=9, "pre", "post"),
         firstlast = if_else(Day==0, "start", if_else(Day==30, "end", "between")))
physeq_format <- phyloseq(physeq@otu_table, physeq@tax_table, physeq@phy_tree, sample_data(meta_format))

# Ordinate 
# Using pcoa because no convergence with nmds
ord_pcoa <- ordinate(physeq_format, method="PCoA", distance=wuni_dist)

# Visualize
plot_ordination(physeq_format, ord_pcoa, color="Inoculant") +
  facet_wrap(~Day) +
  theme_test()

plot_ordination(physeq_format, ord_pcoa, color="firstlast") +
  facet_wrap(~Inoculant) +
  theme_test()
```

PermANOVA:

```{r}
# Overall 
adonis(wuni_dist~Inoculant*Day, data=meta, permutations=999)

# TP 0
meta_day0 <- meta %>% filter(Day==0)
physeq_day0 <- subset_samples(physeq, Day==0)
wuni_day0 <- distance(physeq_day0, method="wunifrac")
adonis(wuni_day0~Inoculant, data=meta_day0, permutations=999)

# TP 30
meta_day30 <- meta %>% filter(Day==30)
physeq_day30 <- subset_samples(physeq, Day==30)
wuni_day30 <- distance(physeq_day30, method="wunifrac")
adonis(wuni_day30~Inoculant, data=meta_day30, permutations=999)
```

## Effect of time on each innoculant

```{r}
# Inoculant 10
meta_inoc10 <- meta %>% filter(Inoculant==10)
physeq_inoc10 <- subset_samples(physeq, Inoculant==10)
wuni_inoc10 <- distance(physeq_inoc10, method="wunifrac")
ad10 <- adonis(wuni_inoc10~Day, data=meta_inoc10, permutations=999)
p10 <- ad10$aov.tab$`Pr(>F)`[1]

# Inoculant 41
meta_inoc41 <- meta %>% filter(Inoculant==41)
physeq_inoc41 <- subset_samples(physeq, Inoculant==41)
wuni_inoc41 <- distance(physeq_inoc41, method="wunifrac")
ad41 <- adonis(wuni_inoc41~Day, data=meta_inoc41, permutations=999)
p41 <- ad41$aov.tab$`Pr(>F)`[1]

# Inoculant 12
meta_inoc12 <- meta %>% filter(Inoculant==12)
physeq_inoc12 <- subset_samples(physeq, Inoculant==12)
wuni_inoc12 <- distance(physeq_inoc12, method="wunifrac")
adonis(wuni_inoc12~Day, data=meta_inoc12, permutations=999)
ad12 <- adonis(wuni_inoc12~Day, data=meta_inoc12, permutations=999)
p12 <- ad12$aov.tab$`Pr(>F)`[1]

# Inoculant 2
meta_inoc2 <- meta %>% filter(Inoculant==2)
physeq_inoc2 <- subset_samples(physeq, Inoculant==2)
wuni_inoc2 <- distance(physeq_inoc2, method="wunifrac")
adonis(wuni_inoc2~Day, data=meta_inoc2, permutations=999)
ad2 <- adonis(wuni_inoc2~Day, data=meta_inoc2, permutations=999)
p2 <- ad2$aov.tab$`Pr(>F)`[1]

# Inoculant 19
meta_inoc19 <- meta %>% filter(Inoculant==19)
physeq_inoc19 <- subset_samples(physeq, Inoculant==19)
wuni_inoc19 <- distance(physeq_inoc19, method="wunifrac")
adonis(wuni_inoc19~Day, data=meta_inoc19, permutations=999)
ad19 <- adonis(wuni_inoc19~Day, data=meta_inoc19, permutations=999)
p19 <- ad19$aov.tab$`Pr(>F)`[1]

# Inoculant 47
meta_inoc47 <- meta %>% filter(Inoculant==47)
physeq_inoc47 <- subset_samples(physeq, Inoculant==47)
wuni_inoc47 <- distance(physeq_inoc47, method="wunifrac")
adonis(wuni_inoc47~Day, data=meta_inoc47, permutations=999)
ad47 <- adonis(wuni_inoc47~Day, data=meta_inoc47, permutations=999)
p47 <- ad47$aov.tab$`Pr(>F)`[1]

# P adjust
p.adjust(c(p10, p2, p41, p47, p12, p19), method="fdr", n=6)

```