---
title: "WIP"
author: "Cassandra Wattenburger"
date: "2/7/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
# Clear working directory, load in packages, generate package info
rm(list=ls())

library("phyloseq")
library("vegan")
library("tidyverse")
library("lmerTest")
library("cowplot")

sessionInfo()

# I can't type "head" apparently so I'm going to make an alias
h <- function(x) {head(x)}
```

# Import data

```{r}
# Metadata
meta <- readRDS("../data_intermediate/SFA2_metadata.rds")

# Growth estimates
growth <- readRDS("../data_intermediate/SFA2_growth_estimates_pap2.rds")

# Death estimates
death <- readRDS("../data_intermediate/SFA2_death_estimates_pap2.rds")

# All paprica estimates
pap_all <- readRDS("../data_intermediate/SFA2_paprica_all.rds")
```

# Growth vs Death

```{r}
growth_death <- growth %>% 
  select(Inoculant, ASV, gr_k=k, deltaNg=change_abund_corr) %>% 
  inner_join(death) %>% 
  select(Inoculant, ASV, gr_k, de_k=k, deltaNg, deltaNd=change_abund_corr) %>% 
  group_by(ASV) %>% # average ASVs across inoculant (for independence)
  summarize(gr_k = mean(gr_k),
            de_k = mean(de_k),
            deltaNg = mean(deltaNg),
            deltaNd = mean(deltaNd))
```

```{r}
# rate
growth_death %>% 
  ggplot(aes(x=gr_k, y=de_k)) +
  geom_point() +
  theme_test()

# deltaN
growth_death %>% 
  ggplot(aes(x=log(deltaNg), y=log(abs(deltaNd)))) +
  geom_point() +
  geom_smooth(method="lm", linetype=2, color="darkgray") +
  theme_test() +
  theme(axis.text = element_text(size=10),
        axis.title = element_blank())
```

```{r}
cor.test(log(growth_death$deltaNg), log(abs(growth_death$deltaNd)), data=growth_death)
```


